language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      env: LANG=cpp CC=gcc CXX=g++
      sudo: required
      dist: trusty
    - os: linux
      compiler: gcc
      env: LANG=cpp CC=gcc-5 CXX=g++-5
      sudo: required
      dist: trusty
    - os: linux
      compiler: gcc
      env: LANG=cpp CC=gcc-6 CXX=g++-6
      sudo: required
      dist: trusty
    - os: linux
      compiler: clang
      env: LANG=cpp CC=clang-3.6 CXX=clang++-3.6
      sudo: required
      dist: trusty
    - os: linux
      compiler: gcc
      env: LANG=php LANG_VERSION=5.6
    - os: linux
      compiler: gcc
      env: LANG=php LANG_VERSION=7.0
    - os: linux
      compiler: gcc
      env: LANG=php LANG_VERSION=7.1
env:
  global:
    - BUILD_DIR_NAME=build
    - DOC_BRANCH=master
    - LIB_LOW_LEVEL_API=ON
    # COVERITY_SCAN_TOKEN
    - secure: "GjN2rHGtPPXTMwWUzpB9ULqDrFXmShysGtQ8VIXYJULUUHZ26entYWuwTb8q3NI8syVeDFyCmam7PSnRgc/nuaOBh8/2lO+dAB1H54jfvbREBBYC2yIIZAT1z/oQ/ZYWdJBrWsNw+pPYk8lY1Z52ggLu2Gd4fktrzuISch7CuCY="
before_install:
  - date -u
  - uname -a
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then lscpu; fi
install:
  - source ./ci/install-credentials.sh
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then source ./ci/install-linux-dependencies.sh; fi
  - ${CC} --version
  - ${CXX} --version
before_script: ./ci/configure.sh
script: ./ci/run.sh
after_success:
  - source ./ci/publish-docs.sh
