language: cpp
matrix:
  include:
  - os: linux
    compiler: gcc
    env: BUILD_DIR_NAME=build
before_install:
  - echo Before install
install:
  - echo Install
before_script:
  - echo Before script
script:
  - echo Script
after_success:
  - echo After success
dist: trusty
sudo: false
