language: php
matrix:
  include:
  - os: linux
    env: TARGET=cpp-gcc

  - os: linux
    php: php7.1
    env: TARGET=PHP7.0

  - os: linux
    php: php7.1
    env: TARGET=PHP7.`
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - libcurl4-openssl-dev
      - g++-5
      - clang-3.6
      - graphviz
before_install:
  - echo Before install
install:
  - echo Install
before_script:
  - echo Before script
script:
  - echo Script
  - php --version || echo "No php"
  - gcc --version || echo "No gcc"
  - clang --version || echo "No clang"
  - echo ${TARGET}
after_success:
  - echo After success
dist: trusty
sudo: false
