language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      env: LANG=php LANG_VERSION=5.6
      sudo: required
      dist: trusty
    - os: linux
      compiler: gcc
      env: LANG=php LANG_VERSION=7.0
      sudo: required
      dist: trusty
    - os: linux
      compiler: gcc
      env: LANG=php LANG_VERSION=7.1
      sudo: required
      dist: trusty
env:
    - PROJECT_ROOT=${TRAVIS_BUILD_DIR}
before_install:
  - date -u
  - uname -a
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then lscpu; fi
install:
  - cd "${TRAVIS_BUILD_DIR}"; if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then source ./ci/install-linux-dependencies.sh; fi
  - ${CC} --version
  - ${CXX} --version
  - echo "=========================================="
  - php-config
  - echo "=========================================="
before_script: echo "Before script"
script: echo "Script"
after_success: echo "After success"
